trigger:
  - main
  - develop
  
pr:
  - main
  - develop

variables:
  - group: sonar-github-alternative
  - name: solution
    value: '*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

steps:
- script: |
    set -ex
    echo "Installing commitlint..."
    npm install -g @commitlint/cli @commitlint/config-conventional

    echo "Getting base commit..."
    BASE_COMMIT=$(git merge-base $(PullRequest.TargetBranch) $(Build.SourceBranchName))

    echo "Linting commits..."
    commitlint --from $BASE_COMMIT --to $(Build.SourceVersion)]
  displayName: 'Lint commit messages'
#  condition: eq(variables['Build.Reason'], 'PullRequest')
